server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/parcial2/api/v1/movies/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/parcial2/api/v1/users/**
        - id: showtime-service
          uri: lb://showtime-service
          predicates:
            - Path=/parcial2/api/v1/showtimes/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/parcial2/api/v1/bookings/**