spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jrestrepo21/parcial2ConfiData.git
  security:
    user:
      name: jrestrepo21
      password: geral020913
server:
  port: 9000

